/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "nynn_mm_constants.h"

namespace nynn { namespace mm {

const nynn_mmConstants g_nynn_mm_constants;

nynn_mmConstants::nynn_mmConstants() {
}

}} // namespace

