/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef nynn_mm_CONSTANTS_H
#define nynn_mm_CONSTANTS_H

#include "nynn_mm_types.h"

namespace nynn { namespace mm {

class nynn_mmConstants {
 public:
  nynn_mmConstants();

};

extern const nynn_mmConstants g_nynn_mm_constants;

}} // namespace

#endif
