// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DataXceiver.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::nynn::mm;

class DataXceiverHandler : virtual public DataXceiverIf {
 public:
  DataXceiverHandler() {
    // Your initialization goes here
  }

  void fetch(std::vector<std::vector<int8_t> > & _return, const int64_t vtxno, const int32_t blkno) {
    // Your implementation goes here
    printf("fetch\n");
  }

  bool post(const std::vector<std::vector<int8_t> > & data) {
    // Your implementation goes here
    printf("post\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<DataXceiverHandler> handler(new DataXceiverHandler());
  shared_ptr<TProcessor> processor(new DataXceiverProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

